secret:
  root_user_password: 'Server_Root_Password'

  firewalld_service:
    - service: 'ssh'
      zone: 'public'
      permanent: 'yes'
      state: 'enabled'
      immediate: true

  firewalld_rich_rules:
    - port: "{{ sshd_port }}"
      protocol: tcp
      control: accept
      ips:
        - 111.222.333.444
        - 111.222.333.445
    - port: "{{ dockerd_port }}"
      protocol: tcp
      control: accept
      ips:
        - 111.222.333.444
        - 111.222.333.445
        - 111.222.333.446
  # users
  # If empty
  # users: []
  users:
    develop_001:
      name: 'develop_001'
      groups: 'wheel,manager'
      append: 'yes'
      state: 'present'
      remove: 'no'
      password: "password"
      public_key: "~/.ssh/ansible_rsa.pub"
      login_shell: '/bin/bash'
      create_home: 'yes'
      sudo: 'absent'
      comment: 'vh1 comment'
      expires: '-1'
      docker_group: true
    develop_002:
      name: 'develop_002'
      groups: 'wheel,manager'
      append: 'yes'
      state: 'present'
      remove: 'no'
      password: "password"
      public_key: "~/.ssh/ansible_rsa.pub"
      login_shell: '/bin/bash'
      create_home: 'yes'
      sudo: 'present'
      comment: 'vh1 comment'
      expires: '-1'
      docker_group: false
