---
# tasks file for roles/firewalld
- name: Install firewalld
  become: yes
  yum:
    name: firewalld
    state: latest

- name: Start firewalld
  become: yes
  systemd:
    state: started
    name: firewalld
    enabled: yes

- name: Open service by firewalld
  become: yes
  firewalld:
    zone: "{{ item.zone }}"
    service: "{{ item.service }}"
    permanent: "{{ item.permanent }}"
    state: "{{ item.state }}"
    immediate: "{{ item.immediate }}"
  with_items: "{{ firewalld_service }}"
  when: firewalld_service is defined
  notify: Restart firewalld

- name: Firewalld setting
  become: yes
  firewalld:
    rich_rule: 'rule family=ipv4 source address="{{ item.1 }}" port port="{{ item.0.port }}" protocol="{{ item.0.protocol }}" "{{ item.0.control }}"'
    permanent: yes
    state: enabled
  with_subelements:
    - "{{ firewalld_rich_rules }}"
    - ips
  notify: Restart firewalld
