---
# tasks file for roles/docer
# For CentOS7
- name: check installed docker
  shell: bash -lc "docker --version"
  register: docker_exists
  changed_when: False
  ignore_errors: yes


- name: Add docker GPG key
  become: yes
  rpm_key:
    key: https://download.docker.com/linux/ubuntu/gpg
  when: docker_exists is failed

- name: add docker repo
  become: yes
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  when: docker_exists is failed

- name: install Docker
  become: yes
  yum:
    name: "{{ item }}"
    state: latest
  with_list: "{{ docker_dependencies }}"
  notify: service_docker_enabled
  when: docker_exists is failed

- name: user add docker group
  become: true
  user:
    name: "{{ item.value.name }}"
    groups: 'docker'
    append: 'yes'
  with_dict: "{{ users }}"
  when:
    - users is defined
    - item.value.docker_group == true

- name: ansible-user add docker group
  become: true
  user:
    name: "{{ ansible_env.USER }}"
    groups: 'docker'
    append: 'yes'

- name: Check exist docker deamon service file
  become: true
  stat:
    path: "/etc/systemd/system/docker.service.d/startup_options.conf"
  register: exists_docker_deamon

- name: Docker deamon dir
  become: true
  file:
    path: "/etc/systemd/system/docker.service.d"
    state: "directory"
  when:
    - exists_docker_deamon.stat.exists == false

- name: Docker deamon service.conf
  become: true
  template:
    src: templates/startup_options.conf.j2
    dest: "/etc/systemd/system/docker.service.d/startup_options.conf"
  when:
    - exists_docker_deamon.stat.exists == false

- name: Docker demon check
  become: true
  shell: |
    bash -lc "service docker status | grep '0.0.0.0:{{ dockerd_port }}' | wc -l"
  changed_when: False
  register: docker_deamon_service

- name: debug
  debug:
    msg: "{{ docker_deamon_service.stdout }}"


- name: Reload systemd docker
  become: true
  shell: |
    bash -lc "systemctl daemon-reload"
    bash -lc "systemctl restart docker.service"
  when:
    - docker_deamon_service.stdout == "0"
